### ISSUE TITLE
Add friendlier errors

### ISSUE THREAD

**Issue by remyleone** [meta-pytorch/torchx#789]
## 🐛 Bug

Module (check all that applies):
 * [ ] `torchx.spec`
 * [ ] `torchx.component`
 * [ ] `torchx.apps`
 * [ ] `torchx.runtime`
 * [x] `torchx.cli`
 * [ ] `torchx.schedulers`
 * [ ] `torchx.pipelines`
 * [ ] `torchx.aws`
 * [ ] `torchx.examples`
 * [ ] `other`

## To Reproduce

```
$ torchx configure       
Traceback (most recent call last):
  File "/Users/rleone/.local/bin/torchx", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/rleone/.local/lib/python3.11/site-packages/torchx/cli/main.py", line 116, in main
    run_main(get_sub_cmds(), argv)
  File "/Users/rleone/.local/lib/python3.11/site-packages/torchx/cli/main.py", line 112, in run_main
    args.func(args)
  File "/Users/rleone/.local/lib/python3.11/site-packages/torchx/cli/cmd_configure.py", line 52, in run
    dump(f=f, schedulers=schedulers, required_only=required_only)
  File "/Users/rleone/.local/lib/python3.11/site-packages/torchx/runner/config.py", line 247, in dump
    sched = _get_scheduler(sched_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rleone/.local/lib/python3.11/site-packages/torchx/runner/config.py", line 203, in _get_scheduler
    sched = schedulers[name](session_name="_")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rleone/.local/lib/python3.11/site-packages/torchx/schedulers/__init__.py", line 37, in run
    module = importlib.import_module(path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/rleone/.local/lib/python3.11/site-packages/torchx/schedulers/ray_scheduler.py", line 446, in <module>
    session_name: str, ray_client: Optional[JobSubmissionClient] = None, **kwargs: Any
                                            ^^^^^^^^^^^^^^^^^^^
NameError: name 'JobSubmissionClient' is not defined

```

## Expected behavior

I would expect an error message with a bit of documentation about what to do to configure my deployments.

## Environment

```
$ torchx --version
torchx-0.6.0

$ python3 --version                               
Python 3.11.5

os: macos 14.1
pip installation
```

**Comment by kiukchung** [comment]
Thanks for reporting! How did you install torchx?

We use extra reqs to install additional scheduler dependencies based on the user's choice of scheduler backend. See: https://github.com/pytorch/torchx#stable.

For ray, I'm wondering if you installed it via:

```
pip install torchx[ray]
```

as suggested in the docs.

**Comment by remyleone** [comment]
I've installed it using only `pip install torchx` I've tried to install it using `pip install torchx[dev]` but it took many hours on my setup and was not successful at the end. I think there was an issues with the dependencies. https://pytorch.org/torchx/main/quickstart.html

**Comment by kiukchung** [comment]
Ah this is due to the changes in `pip`'s dependency resolution logic for `python-3.11`. Pip now backtracks deps and unfortunately, it needs to actually download wheels of direct deps to figure out transitive deps. This is why you're seeing so many versions of `kubernetes` being downloaded. You can fall back to the previous logic by:

```
pip install --use-deprecated=legacy-resolver -e .[dev]
```

Which is what we do for CI (see [workflow](https://github.com/pytorch/torchx/blob/main/.github/workflows/python-unittests.yaml#L38C11-L38C54)).

I created a bug report to track and fix https://github.com/pytorch/torchx/issues/790.

**Comment by kiukchung** [comment]
Closing: `torchx configure` no longer raises. On current `main` `torchx configure --print` prints the per-scheduler config sections and exits 0. If you hit an unfriendly error elsewhere in the CLI, please open a new issue with that specific traceback.
